/*
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 *
 * Please pay attention. This is the refactory of the ObjectFactory
 * class geberated by xjc when it processes the wm_pool.xsd file.
 * In case you need to change vm_types.xsd, please run 
 * 
 * xjc -d ../src/ -p org.opennebula.xmlschema.compute -verbose vm_pool.xsd 
 *
 * then check ObjectFactory.java with this file and import any changes
 * (except class name) from ObjectFactory.java into this file.
 *
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.24 at 01:21:00 PM CEST 
//


package org.opennebula.xmlschema.compute;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.compute package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class VMCOMPLEXObjectFactory {

    private final static QName _VM_QNAME = new QName("http://opennebula.org/XMLSchema", "VM");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.compute
     * 
     */
    public VMCOMPLEXObjectFactory() {
    }

    /**
     * Create an instance of {@link OsType }
     * 
     */
    public OsType createOsType() {
        return new OsType();
    }

    /**
     * Create an instance of {@link DiskType }
     * 
     */
    public DiskType createDiskType() {
        return new DiskType();
    }

    /**
     * Create an instance of {@link VMPOOL }
     * 
     */
    public VMPOOL createVMPOOL() {
        return new VMPOOL();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link VMSIMPLE }
     * 
     */
    public VMSIMPLE createVMSIMPLE() {
        return new VMSIMPLE();
    }

    /**
     * Create an instance of {@link NicType }
     * 
     */
    public NicType createNicType() {
        return new NicType();
    }

    /**
     * Create an instance of {@link VMCOMPLEX }
     * 
     */
    public VMCOMPLEX createVMCOMPLEX() {
        return new VMCOMPLEX();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VMCOMPLEX }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://opennebula.org/XMLSchema", name = "VM")
    public JAXBElement<VMCOMPLEX> createVM(VMCOMPLEX value) {
        return new JAXBElement<VMCOMPLEX>(_VM_QNAME, VMCOMPLEX.class, null, value);
    }

}
