//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.24 at 01:17:03 PM CEST 
//


package org.opennebula.xmlschema.compute;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.compute package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class VMSIMPLEObjectFactory {

    private final static QName _VM_QNAME = new QName("http://opennebula.org/XMLSchema", "VM");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.compute
     * 
     */
    public VMSIMPLEObjectFactory() {
    }

    /**
     * Create an instance of {@link DiskType }
     * 
     */
    public DiskType createDiskType() {
        return new DiskType();
    }

    /**
     * Create an instance of {@link OsType }
     * 
     */
    public OsType createOsType() {
        return new OsType();
    }

    /**
     * Create an instance of {@link VMCOMPLEX }
     * 
     */
    public VMCOMPLEX createVMCOMPLEX() {
        return new VMCOMPLEX();
    }

    /**
     * Create an instance of {@link NicType }
     * 
     */
    public NicType createNicType() {
        return new NicType();
    }

    /**
     * Create an instance of {@link VMSIMPLE }
     * 
     */
    public VMSIMPLE createVMSIMPLE() {
        return new VMSIMPLE();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VMSIMPLE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://opennebula.org/XMLSchema", name = "VM")
    public JAXBElement<VMSIMPLE> createVM(VMSIMPLE value) {
        return new JAXBElement<VMSIMPLE>(_VM_QNAME, VMSIMPLE.class, null, value);
    }

}
