//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.24 at 04:09:38 PM CET 
//


package org.w3._2001.xmlschema;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, String>
{


    public String unmarshal(String value) {
        return (javax.xml.bind.DatatypeConverter.parseAnySimpleType(value));
    }

    public String marshal(String value) {
        if (value == null) {
            return null;
        }
        return (javax.xml.bind.DatatypeConverter.printAnySimpleType(value));
    }

}
