//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.24 at 06:18:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dmtf.schemas.wbem.wscim._1.cim_schema._2.cim_virtualsystemsettingdata;
