//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:11 PM CEST 
//


package org.opennebula.xmlschema.vmpool;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.vmpool package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VMPOOL_QNAME = new QName("", "VM_POOL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.vmpool
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VirtualMachinePool }
     * 
     */
    public VirtualMachinePool createVirtualMachinePool() {
        return new VirtualMachinePool();
    }

    /**
     * Create an instance of {@link VirtualMachineHistory }
     * 
     */
    public VirtualMachineHistory createVirtualMachineHistory() {
        return new VirtualMachineHistory();
    }

    /**
     * Create an instance of {@link VirtualMachine }
     * 
     */
    public VirtualMachine createVirtualMachine() {
        return new VirtualMachine();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirtualMachinePool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VM_POOL")
    public JAXBElement<VirtualMachinePool> createVMPOOL(VirtualMachinePool value) {
        return new JAXBElement<VirtualMachinePool>(_VMPOOL_QNAME, VirtualMachinePool.class, null, value);
    }

}
