//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:09 PM CEST 
//


package org.opennebula.xmlschema.hostpool;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HostShare complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostShare">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="DISK_USAGE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MEM_USAGE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CPU_USAGE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MAX_DISK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MAX_MEM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MAX_CPU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FREE_DISK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FREE_MEM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FREE_CPU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="USED_DISK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="USED_MEM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="USED_CPU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RUNNING_VMS" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostShare", propOrder = {
    "hid",
    "diskusage",
    "memusage",
    "cpuusage",
    "maxdisk",
    "maxmem",
    "maxcpu",
    "freedisk",
    "freemem",
    "freecpu",
    "useddisk",
    "usedmem",
    "usedcpu",
    "runningvms"
})
public class HostShare {

    @XmlElement(name = "HID")
    protected int hid;
    @XmlElement(name = "DISK_USAGE")
    protected int diskusage;
    @XmlElement(name = "MEM_USAGE")
    protected int memusage;
    @XmlElement(name = "CPU_USAGE")
    protected int cpuusage;
    @XmlElement(name = "MAX_DISK")
    protected int maxdisk;
    @XmlElement(name = "MAX_MEM")
    protected int maxmem;
    @XmlElement(name = "MAX_CPU")
    protected int maxcpu;
    @XmlElement(name = "FREE_DISK")
    protected int freedisk;
    @XmlElement(name = "FREE_MEM")
    protected int freemem;
    @XmlElement(name = "FREE_CPU")
    protected int freecpu;
    @XmlElement(name = "USED_DISK")
    protected int useddisk;
    @XmlElement(name = "USED_MEM")
    protected int usedmem;
    @XmlElement(name = "USED_CPU")
    protected int usedcpu;
    @XmlElement(name = "RUNNING_VMS")
    protected int runningvms;

    /**
     * Gets the value of the hid property.
     * 
     */
    public int getHID() {
        return hid;
    }

    /**
     * Sets the value of the hid property.
     * 
     */
    public void setHID(int value) {
        this.hid = value;
    }

    /**
     * Gets the value of the diskusage property.
     * 
     */
    public int getDISKUSAGE() {
        return diskusage;
    }

    /**
     * Sets the value of the diskusage property.
     * 
     */
    public void setDISKUSAGE(int value) {
        this.diskusage = value;
    }

    /**
     * Gets the value of the memusage property.
     * 
     */
    public int getMEMUSAGE() {
        return memusage;
    }

    /**
     * Sets the value of the memusage property.
     * 
     */
    public void setMEMUSAGE(int value) {
        this.memusage = value;
    }

    /**
     * Gets the value of the cpuusage property.
     * 
     */
    public int getCPUUSAGE() {
        return cpuusage;
    }

    /**
     * Sets the value of the cpuusage property.
     * 
     */
    public void setCPUUSAGE(int value) {
        this.cpuusage = value;
    }

    /**
     * Gets the value of the maxdisk property.
     * 
     */
    public int getMAXDISK() {
        return maxdisk;
    }

    /**
     * Sets the value of the maxdisk property.
     * 
     */
    public void setMAXDISK(int value) {
        this.maxdisk = value;
    }

    /**
     * Gets the value of the maxmem property.
     * 
     */
    public int getMAXMEM() {
        return maxmem;
    }

    /**
     * Sets the value of the maxmem property.
     * 
     */
    public void setMAXMEM(int value) {
        this.maxmem = value;
    }

    /**
     * Gets the value of the maxcpu property.
     * 
     */
    public int getMAXCPU() {
        return maxcpu;
    }

    /**
     * Sets the value of the maxcpu property.
     * 
     */
    public void setMAXCPU(int value) {
        this.maxcpu = value;
    }

    /**
     * Gets the value of the freedisk property.
     * 
     */
    public int getFREEDISK() {
        return freedisk;
    }

    /**
     * Sets the value of the freedisk property.
     * 
     */
    public void setFREEDISK(int value) {
        this.freedisk = value;
    }

    /**
     * Gets the value of the freemem property.
     * 
     */
    public int getFREEMEM() {
        return freemem;
    }

    /**
     * Sets the value of the freemem property.
     * 
     */
    public void setFREEMEM(int value) {
        this.freemem = value;
    }

    /**
     * Gets the value of the freecpu property.
     * 
     */
    public int getFREECPU() {
        return freecpu;
    }

    /**
     * Sets the value of the freecpu property.
     * 
     */
    public void setFREECPU(int value) {
        this.freecpu = value;
    }

    /**
     * Gets the value of the useddisk property.
     * 
     */
    public int getUSEDDISK() {
        return useddisk;
    }

    /**
     * Sets the value of the useddisk property.
     * 
     */
    public void setUSEDDISK(int value) {
        this.useddisk = value;
    }

    /**
     * Gets the value of the usedmem property.
     * 
     */
    public int getUSEDMEM() {
        return usedmem;
    }

    /**
     * Sets the value of the usedmem property.
     * 
     */
    public void setUSEDMEM(int value) {
        this.usedmem = value;
    }

    /**
     * Gets the value of the usedcpu property.
     * 
     */
    public int getUSEDCPU() {
        return usedcpu;
    }

    /**
     * Sets the value of the usedcpu property.
     * 
     */
    public void setUSEDCPU(int value) {
        this.usedcpu = value;
    }

    /**
     * Gets the value of the runningvms property.
     * 
     */
    public int getRUNNINGVMS() {
        return runningvms;
    }

    /**
     * Sets the value of the runningvms property.
     * 
     */
    public void setRUNNINGVMS(int value) {
        this.runningvms = value;
    }

}
