//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:09 PM CEST 
//


package org.opennebula.xmlschema.hostpool;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Host complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Host">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="IM_MAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VM_MAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TM_MAD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LAST_MON_TIME" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="HOST_SHARE" type="{}HostShare"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Host", propOrder = {
    "id",
    "name",
    "state",
    "immad",
    "vmmad",
    "tmmad",
    "lastmontime",
    "hostshare"
})
public class Host {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "STATE")
    protected int state;
    @XmlElement(name = "IM_MAD", required = true)
    protected String immad;
    @XmlElement(name = "VM_MAD", required = true)
    protected String vmmad;
    @XmlElement(name = "TM_MAD", required = true)
    protected String tmmad;
    @XmlElement(name = "LAST_MON_TIME")
    protected int lastmontime;
    @XmlElement(name = "HOST_SHARE", required = true)
    protected HostShare hostshare;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the state property.
     * 
     */
    public int getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     */
    public void setSTATE(int value) {
        this.state = value;
    }

    /**
     * Gets the value of the immad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMMAD() {
        return immad;
    }

    /**
     * Sets the value of the immad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMMAD(String value) {
        this.immad = value;
    }

    /**
     * Gets the value of the vmmad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVMMAD() {
        return vmmad;
    }

    /**
     * Sets the value of the vmmad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVMMAD(String value) {
        this.vmmad = value;
    }

    /**
     * Gets the value of the tmmad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTMMAD() {
        return tmmad;
    }

    /**
     * Sets the value of the tmmad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTMMAD(String value) {
        this.tmmad = value;
    }

    /**
     * Gets the value of the lastmontime property.
     * 
     */
    public int getLASTMONTIME() {
        return lastmontime;
    }

    /**
     * Sets the value of the lastmontime property.
     * 
     */
    public void setLASTMONTIME(int value) {
        this.lastmontime = value;
    }

    /**
     * Gets the value of the hostshare property.
     * 
     * @return
     *     possible object is
     *     {@link HostShare }
     *     
     */
    public HostShare getHOSTSHARE() {
        return hostshare;
    }

    /**
     * Sets the value of the hostshare property.
     * 
     * @param value
     *     allowed object is
     *     {@link HostShare }
     *     
     */
    public void setHOSTSHARE(HostShare value) {
        this.hostshare = value;
    }

}
