//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:09 PM CEST 
//


package org.opennebula.xmlschema.hostpool;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.hostpool package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HOSTPOOL_QNAME = new QName("", "HOST_POOL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.hostpool
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HostShare }
     * 
     */
    public HostShare createHostShare() {
        return new HostShare();
    }

    /**
     * Create an instance of {@link HostPool }
     * 
     */
    public HostPool createHostPool() {
        return new HostPool();
    }

    /**
     * Create an instance of {@link Host }
     * 
     */
    public Host createHost() {
        return new Host();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostPool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_POOL")
    public JAXBElement<HostPool> createHOSTPOOL(HostPool value) {
        return new JAXBElement<HostPool>(_HOSTPOOL_QNAME, HostPool.class, null, value);
    }

}
