//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:12 PM CEST 
//


package org.opennebula.xmlschema.netpool;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.netpool package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VNETPOOL_QNAME = new QName("", "VNET_POOL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.netpool
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VirtualNetworkPool }
     * 
     */
    public VirtualNetworkPool createVirtualNetworkPool() {
        return new VirtualNetworkPool();
    }

    /**
     * Create an instance of {@link VirtualNetwork }
     * 
     */
    public VirtualNetwork createVirtualNetwork() {
        return new VirtualNetwork();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirtualNetworkPool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VNET_POOL")
    public JAXBElement<VirtualNetworkPool> createVNETPOOL(VirtualNetworkPool value) {
        return new JAXBElement<VirtualNetworkPool>(_VNETPOOL_QNAME, VirtualNetworkPool.class, null, value);
    }

}
