//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:12 PM CEST 
//


package org.opennebula.xmlschema.netpool;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualNetwork complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualNetwork">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="USERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="BRIDGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TOTAL_LEASES" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualNetwork", propOrder = {
    "id",
    "uid",
    "username",
    "name",
    "type",
    "bridge",
    "totalleases"
})
public class VirtualNetwork {

    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "UID")
    protected int uid;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "TYPE")
    protected int type;
    @XmlElement(name = "BRIDGE", required = true)
    protected String bridge;
    @XmlElement(name = "TOTAL_LEASES")
    protected int totalleases;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public int getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public void setUID(int value) {
        this.uid = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     */
    public int getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     */
    public void setTYPE(int value) {
        this.type = value;
    }

    /**
     * Gets the value of the bridge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRIDGE() {
        return bridge;
    }

    /**
     * Sets the value of the bridge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRIDGE(String value) {
        this.bridge = value;
    }

    /**
     * Gets the value of the totalleases property.
     * 
     */
    public int getTOTALLEASES() {
        return totalleases;
    }

    /**
     * Sets the value of the totalleases property.
     * 
     */
    public void setTOTALLEASES(int value) {
        this.totalleases = value;
    }

}
