//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:10 PM CEST 
//


package org.opennebula.xmlschema.vm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.vm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VM_QNAME = new QName("", "VM");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.vm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsHistory }
     * 
     */
    public VirtualMachineDetailsHistory createVirtualMachineDetailsHistory() {
        return new VirtualMachineDetailsHistory();
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsOS }
     * 
     */
    public VirtualMachineDetailsOS createVirtualMachineDetailsOS() {
        return new VirtualMachineDetailsOS();
    }

    /**
     * Create an instance of {@link VirtualMachineDetails }
     * 
     */
    public VirtualMachineDetails createVirtualMachineDetails() {
        return new VirtualMachineDetails();
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsTemplate }
     * 
     */
    public VirtualMachineDetailsTemplate createVirtualMachineDetailsTemplate() {
        return new VirtualMachineDetailsTemplate();
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsNIC }
     * 
     */
    public VirtualMachineDetailsNIC createVirtualMachineDetailsNIC() {
        return new VirtualMachineDetailsNIC();
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsGraphics }
     * 
     */
    public VirtualMachineDetailsGraphics createVirtualMachineDetailsGraphics() {
        return new VirtualMachineDetailsGraphics();
    }

    /**
     * Create an instance of {@link VirtualMachineDetailsDisk }
     * 
     */
    public VirtualMachineDetailsDisk createVirtualMachineDetailsDisk() {
        return new VirtualMachineDetailsDisk();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirtualMachineDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VM")
    public JAXBElement<VirtualMachineDetails> createVM(VirtualMachineDetails value) {
        return new JAXBElement<VirtualMachineDetails>(_VM_QNAME, VirtualMachineDetails.class, null, value);
    }

}
