//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:10 PM CEST 
//


package org.opennebula.xmlschema.vm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualMachineDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualMachineDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LAST_POLL" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LCM_STATE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="STIME" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ETIME" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="DEPLOY_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MEMORY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CPU" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NET_TX" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NET_RX" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TEMPLATE" type="{}VirtualMachineDetailsTemplate"/>
 *         &lt;element name="HISTORY" type="{}VirtualMachineDetailsHistory"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachineDetails", propOrder = {
    "id",
    "uid",
    "name",
    "lastpoll",
    "state",
    "lcmstate",
    "stime",
    "etime",
    "deployid",
    "memory",
    "cpu",
    "nettx",
    "netrx",
    "template",
    "history"
})
public class VirtualMachineDetails {

    @XmlElement(name = "ID")
    protected long id;
    @XmlElement(name = "UID")
    protected int uid;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "LAST_POLL")
    protected long lastpoll;
    @XmlElement(name = "STATE")
    protected int state;
    @XmlElement(name = "LCM_STATE")
    protected int lcmstate;
    @XmlElement(name = "STIME")
    protected long stime;
    @XmlElement(name = "ETIME")
    protected long etime;
    @XmlElement(name = "DEPLOY_ID", required = true)
    protected String deployid;
    @XmlElement(name = "MEMORY")
    protected int memory;
    @XmlElement(name = "CPU")
    protected int cpu;
    @XmlElement(name = "NET_TX")
    protected int nettx;
    @XmlElement(name = "NET_RX")
    protected int netrx;
    @XmlElement(name = "TEMPLATE", required = true)
    protected VirtualMachineDetailsTemplate template;
    @XmlElement(name = "HISTORY", required = true)
    protected VirtualMachineDetailsHistory history;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public int getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public void setUID(int value) {
        this.uid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lastpoll property.
     * 
     */
    public long getLASTPOLL() {
        return lastpoll;
    }

    /**
     * Sets the value of the lastpoll property.
     * 
     */
    public void setLASTPOLL(long value) {
        this.lastpoll = value;
    }

    /**
     * Gets the value of the state property.
     * 
     */
    public int getSTATE() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     */
    public void setSTATE(int value) {
        this.state = value;
    }

    /**
     * Gets the value of the lcmstate property.
     * 
     */
    public int getLCMSTATE() {
        return lcmstate;
    }

    /**
     * Sets the value of the lcmstate property.
     * 
     */
    public void setLCMSTATE(int value) {
        this.lcmstate = value;
    }

    /**
     * Gets the value of the stime property.
     * 
     */
    public long getSTIME() {
        return stime;
    }

    /**
     * Sets the value of the stime property.
     * 
     */
    public void setSTIME(long value) {
        this.stime = value;
    }

    /**
     * Gets the value of the etime property.
     * 
     */
    public long getETIME() {
        return etime;
    }

    /**
     * Sets the value of the etime property.
     * 
     */
    public void setETIME(long value) {
        this.etime = value;
    }

    /**
     * Gets the value of the deployid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDEPLOYID() {
        return deployid;
    }

    /**
     * Sets the value of the deployid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDEPLOYID(String value) {
        this.deployid = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     */
    public int getMEMORY() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     */
    public void setMEMORY(int value) {
        this.memory = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     */
    public int getCPU() {
        return cpu;
    }

    /**
     * Sets the value of the cpu property.
     * 
     */
    public void setCPU(int value) {
        this.cpu = value;
    }

    /**
     * Gets the value of the nettx property.
     * 
     */
    public int getNETTX() {
        return nettx;
    }

    /**
     * Sets the value of the nettx property.
     * 
     */
    public void setNETTX(int value) {
        this.nettx = value;
    }

    /**
     * Gets the value of the netrx property.
     * 
     */
    public int getNETRX() {
        return netrx;
    }

    /**
     * Sets the value of the netrx property.
     * 
     */
    public void setNETRX(int value) {
        this.netrx = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachineDetailsTemplate }
     *     
     */
    public VirtualMachineDetailsTemplate getTEMPLATE() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachineDetailsTemplate }
     *     
     */
    public void setTEMPLATE(VirtualMachineDetailsTemplate value) {
        this.template = value;
    }

    /**
     * Gets the value of the history property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualMachineDetailsHistory }
     *     
     */
    public VirtualMachineDetailsHistory getHISTORY() {
        return history;
    }

    /**
     * Sets the value of the history property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualMachineDetailsHistory }
     *     
     */
    public void setHISTORY(VirtualMachineDetailsHistory value) {
        this.history = value;
    }

}
