//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:10 PM CEST 
//


package org.opennebula.xmlschema.vm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualMachineDetailsDisk complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualMachineDetailsDisk">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CLONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="READONLY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SAVE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TARGET" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachineDetailsDisk", propOrder = {
    "clone",
    "readonly",
    "save",
    "source",
    "target",
    "type"
})
public class VirtualMachineDetailsDisk {

    @XmlElement(name = "CLONE", required = true)
    protected String clone;
    @XmlElement(name = "READONLY", required = true)
    protected String readonly;
    @XmlElement(name = "SAVE", required = true)
    protected String save;
    @XmlElement(name = "SOURCE", required = true)
    protected String source;
    @XmlElement(name = "TARGET", required = true)
    protected String target;
    @XmlElement(name = "TYPE", required = true)
    protected String type;

    /**
     * Gets the value of the clone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLONE() {
        return clone;
    }

    /**
     * Sets the value of the clone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLONE(String value) {
        this.clone = value;
    }

    /**
     * Gets the value of the readonly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREADONLY() {
        return readonly;
    }

    /**
     * Sets the value of the readonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREADONLY(String value) {
        this.readonly = value;
    }

    /**
     * Gets the value of the save property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAVE() {
        return save;
    }

    /**
     * Sets the value of the save property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAVE(String value) {
        this.save = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTARGET() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTARGET(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

}
