//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 08:02:58 PM CEST 
//


package org.opennebula.xmlschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VNET_QNAME = new QName("http://opennebula.org/XMLSchema", "VNET");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VNET.LEASES.LEASE }
     * 
     */
    public VNET.LEASES.LEASE createVNETLEASESLEASE() {
        return new VNET.LEASES.LEASE();
    }

    /**
     * Create an instance of {@link VNET }
     * 
     */
    public VNET createVNET() {
        return new VNET();
    }

    /**
     * Create an instance of {@link VNET.LEASES }
     * 
     */
    public VNET.LEASES createVNETLEASES() {
        return new VNET.LEASES();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VNET }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://opennebula.org/XMLSchema", name = "VNET")
    public JAXBElement<VNET> createVNET(VNET value) {
        return new JAXBElement<VNET>(_VNET_QNAME, VNET.class, null, value);
    }

}
