//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 05:41:33 PM CEST 
//


package org.opennebula.xmlschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ARCH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BOOT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BOOTLOADER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INITRD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KERNEL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KERNEL_CMD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ROOT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsType", propOrder = {
    "arch",
    "boot",
    "bootloader",
    "initrd",
    "kernel",
    "kernelcmd",
    "root"
})
public class OsType {

    @XmlElement(name = "ARCH")
    protected String arch;
    @XmlElement(name = "BOOT")
    protected String boot;
    @XmlElement(name = "BOOTLOADER")
    protected String bootloader;
    @XmlElement(name = "INITRD")
    protected String initrd;
    @XmlElement(name = "KERNEL")
    protected String kernel;
    @XmlElement(name = "KERNEL_CMD")
    protected String kernelcmd;
    @XmlElement(name = "ROOT")
    protected String root;

    /**
     * Gets the value of the arch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARCH() {
        return arch;
    }

    /**
     * Sets the value of the arch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARCH(String value) {
        this.arch = value;
    }

    /**
     * Gets the value of the boot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOOT() {
        return boot;
    }

    /**
     * Sets the value of the boot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOOT(String value) {
        this.boot = value;
    }

    /**
     * Gets the value of the bootloader property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOOTLOADER() {
        return bootloader;
    }

    /**
     * Sets the value of the bootloader property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOOTLOADER(String value) {
        this.bootloader = value;
    }

    /**
     * Gets the value of the initrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINITRD() {
        return initrd;
    }

    /**
     * Sets the value of the initrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINITRD(String value) {
        this.initrd = value;
    }

    /**
     * Gets the value of the kernel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKERNEL() {
        return kernel;
    }

    /**
     * Sets the value of the kernel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKERNEL(String value) {
        this.kernel = value;
    }

    /**
     * Gets the value of the kernelcmd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKERNELCMD() {
        return kernelcmd;
    }

    /**
     * Sets the value of the kernelcmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKERNELCMD(String value) {
        this.kernelcmd = value;
    }

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROOT() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROOT(String value) {
        this.root = value;
    }

}
