//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 02:31:04 PM CEST 
//


package org.opennebula.xmlschema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TemplateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TemplateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CONTEXT" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="CPU" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DISK" type="{http://opennebula.org/XMLSchema}DiskType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MEMORY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NIC" type="{http://opennebula.org/XMLSchema}NicType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OS" type="{http://opennebula.org/XMLSchema}OsType" minOccurs="0"/>
 *         &lt;element name="VCPU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VMID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TemplateType", propOrder = {
    "context",
    "cpu",
    "disk",
    "memory",
    "name",
    "nic",
    "os",
    "vcpu",
    "vmid"
})
public class TemplateType {

    @XmlElement(name = "CONTEXT", required = true)
    protected Object context;
    @XmlElement(name = "CPU")
    protected BigInteger cpu;
    @XmlElement(name = "DISK")
    protected List<DiskType> disk;
    @XmlElement(name = "MEMORY")
    protected String memory;
    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "NIC")
    protected List<NicType> nic;
    @XmlElement(name = "OS")
    protected OsType os;
    @XmlElement(name = "VCPU")
    protected String vcpu;
    @XmlElement(name = "VMID")
    protected String vmid;

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCONTEXT() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCONTEXT(Object value) {
        this.context = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCPU() {
        return cpu;
    }

    /**
     * Sets the value of the cpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCPU(BigInteger value) {
        this.cpu = value;
    }

    /**
     * Gets the value of the disk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDISK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiskType }
     * 
     * 
     */
    public List<DiskType> getDISK() {
        if (disk == null) {
            disk = new ArrayList<DiskType>();
        }
        return this.disk;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMORY() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMORY(String value) {
        this.memory = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNIC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NicType }
     * 
     * 
     */
    public List<NicType> getNIC() {
        if (nic == null) {
            nic = new ArrayList<NicType>();
        }
        return this.nic;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link OsType }
     *     
     */
    public OsType getOS() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link OsType }
     *     
     */
    public void setOS(OsType value) {
        this.os = value;
    }

    /**
     * Gets the value of the vcpu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVCPU() {
        return vcpu;
    }

    /**
     * Sets the value of the vcpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVCPU(String value) {
        this.vcpu = value;
    }

    /**
     * Gets the value of the vmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVMID() {
        return vmid;
    }

    /**
     * Sets the value of the vmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVMID(String value) {
        this.vmid = value;
    }

}
