//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.17 at 06:51:09 PM CEST 
//


package org.opennebula.xmlschema.host;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opennebula.xmlschema.host package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HOST_QNAME = new QName("", "HOST");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opennebula.xmlschema.host
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HostDetailsTemplate }
     * 
     */
    public HostDetailsTemplate createHostDetailsTemplate() {
        return new HostDetailsTemplate();
    }

    /**
     * Create an instance of {@link HostDetails }
     * 
     */
    public HostDetails createHostDetails() {
        return new HostDetails();
    }

    /**
     * Create an instance of {@link HostDetailsShare }
     * 
     */
    public HostDetailsShare createHostDetailsShare() {
        return new HostDetailsShare();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST")
    public JAXBElement<HostDetails> createHOST(HostDetails value) {
        return new JAXBElement<HostDetails>(_HOST_QNAME, HostDetails.class, null, value);
    }

}
